### ISSUE TITLE
goagent OPTIONS 能解决吗？

### ISSUE THREAD

**Issue by gosex** [Alvin9999/new-pac#49]
GOA 3.2.3
ERROR - [Mar 20 08:08:08] create_http_request "OPTIONS https://api.twitter.com/1.1/favorites/create.json" failed:timed out
Traceback (most recent call last):
File "goagent\local\proxylib.py", line 2078, in create_http_request
File "goagent\local\proxylib.py", line 2057, in create_ssl_connection
timeout: timed out

大神，能通过修改代码解决问题不 ？

**Comment by caofengzi** [comment]
這個問題應該無解。

**Comment by Alvin9999** [comment]
楼上正解。楼主不妨可以试下GoProxy版或者PAC版
